### ISSUE TITLE
Dsl.future throws JavaScriptException: findDOMNode was called on an unmounted component

### ISSUE THREAD

**Issue by jcrosetto** [japgolly/test-state#7] opened 2017-01-10 21:46 UTC
I followed the React example to set up a TestState, Dsl, and Test suite. Everything seems to work fine using the synchronous Dsl. However, when using Dsl.future I'm getting the exception: `scala.scalajs.js.JavaScriptException: Invariant Violation: findDOMNode was called on an unmounted component.`

When using Dsl.future, the component is initially mounted but it is no longer  mounted when the `observe()` method gets called. Here's my runTest
```scala
  def runTest(plan: dsl.Plan): Future[Report[String]] = {
    ReactTestUtils.withRenderedIntoBody(MyComponent()) { c =>

      def observe() = {
        println(s"creating observer: ${c.isMounted()}") // c.isMounted() returns false
        new MyComponentObs(c.htmlDomZipper)
      }

      val test = plan
        .addInvariants(invariants)
        .test(Observer watch observe())

      test.runU()
    }
  }
```

And I call it using:
```scala
runTest(plan).map {
    m => m.assert()
}
```

**Comment by japgolly** [comment] 2017-01-16 06:17
Hi @jcrosetto. Yes, that's not obvious but it does make sense. The problem is different execution contexts / effect types are being mixed. If we look at the signature of:
```scala
// ReactTestUtils:
def withRenderedIntoBody[A](c: ReactElement)(f: ComponentM => A): A
```
we can see that, when your `f` function is given a mounted component, whatever it synchronously returns (`A`), is synchronously returned in the end. Side-effects aren't represented in the types, and occur immediately, meaning that as soon as the result is available, the component is unmounted.

Which is what you're experiencing. The future is created, returned, then the component is unmounted before the future completes. Because `ReactTestUtils.withRenderedIntoBody` is synchronous you're going to have to make the body synchronous too. Alternatively, you could create an async version of `withRenderedIntoBody` like this:
```scala
// ReactTestUtils:
def withRenderedIntoBodyAsync[A](c: ReactElement)(f: ComponentM => Future[A]): Future[A]
```

**Comment by jcrosetto** [comment] 2017-01-17 18:59
Thanks @japgolly. Creating the `withRenderedIntoBodyAsync` works perfectly.

**Comment by japgolly** [comment] 2017-01-29 04:27
Awesome to hear it. Let's close this then.

That `withRenderedIntoBodyAsync` method sounds like it'd be a good addition to scalajs-react. Would you mind creating a PR?

**Closed by japgolly** 2017-01-29 04:27 UTC

**Comment by jcrosetto** [comment] 2017-02-03 23:40
Sounds good. I'll work on creating something that mimics what is there for non-async methods.

**Comment by jcrosetto** [comment] 2017-02-06 17:30
Added a PR https://github.com/japgolly/scalajs-react/pull/328. @japgolly Let me know if there is anything I should add or change!
